### ISSUE TITLE
Monk LTS not using Elixir Field or Rising Phoenix in Manual mode

### ISSUE THREAD

**Issue by Playto3** [FFXIV-CombatReborn/LTSDefaults#29]
Elixir Field and Rising Phoenix don't appear to work in Manual Mode. Even with Single target AoE actions enabled for manual mode, they don't seem to appear in the next action window either. Phantom Rush works fine. They seem to work in auto mode but not manual. I thought it would be my settings before hand so I reset everything and still nothing.

**Comment by LTS-FFXIV** [comment]
Elixir Field and Rising Phoenix are not "Single Target AOE actions', they are general AOE actions that do not require a target and therefore are not enabled in manual mode, which is a safety/"burst this mob" mode for targeting one mob at a time. Phantom Rush does require a target and is allowed in manual mode because of it
